### ISSUE TITLE
Index rectifier function throws an error due to not having access to OpenSearch

### ISSUE THREAD

**Issue by paulpilone** [iodepo/OceanBestPractices#280]
The index rectifier function (meant to diff DSpace with our index on a regular schedule) is not deployed into our VPC and therefore can't access OpenSearch. The function throws an error on every invocation due to this issue.

The function needs to be moved into the default VPC so that it can access OpenSearch. The function also (as written) needs to access DSpace. Need to verify that the networking is set up correctly to access the internet while also being deployed within the VPC.

**Comment by arnounesco** [comment]
any news on this?

**Comment by paulpilone** [comment]
@arnounesco I have a draft PR for this fix #282 but sent an email to you and @paulineobps with a clarifying question. When I dry run this function in production I get no results for items-to-be-deleted.

I'm making the assumption in this function that if an item is to be deleted it should return a 404 (or empty response) from DSpace. Is this assumption correct? Is there a different way to identify a "deleted" item? Is there an example of an item that should not exist in the search index but does and I can use that to figure this out?

**Comment by paulineobps** [comment]
Hi Paul

I am replying because Arno is of sick.

The best example of a deleted DSpace record is author BOUHALI that can still be found through the AWI EDS search interface and should not be, if the bulk indexing was working.  When clicking the title it then goes to a  a 'Not Found' screen.  In the withdrawn items it is https://repository.oceanbestpractices.org/admin/item?itemID=548d0be7-8c1f-4e2b-bf09-3551f0ad4718

Hope that helps

Pauline
Pauline SIMPSON
Ocean Best Practices System Project Manager
https://www.oceanbestpractices.org/

UNESCO /IOC Project Office for IODE, InnovOcean Campus – Jacobsenstraat 1 8400 Oostende, Belgium
Email: ***@***.******@***.***>;   Alternate email: ***@***.******@***.***>; Skype: Pauline Simpson
ORCID: 0000-0003-2551-5740


<http://www.iode.org>


________________________________

**Comment by paulpilone** [comment]
@paulineobps Thanks! When I click that link it asks me to sign in or register as a user. It looks like that link is an admin endpoint?

If I try and fetch that item via the DSpace API (how the search interface interacts with DSpace) I get a 401 Unauthorized response - e.g. https://repository.oceanbestpractices.org/rest/items/548d0be7-8c1f-4e2b-bf09-3551f0ad4718?expand=all

Are withdrawn items not available via the regular API?

**Comment by paulpilone** [comment]
Are you using DSpace v6 or v7? It looks like the v7 API supports getting metadata for a withdrawn item as an anonymous user: https://github.com/DSpace/RestContract/blob/main/items.md#withdrawn-item but the v6 API does not.

This is a problem since there's no way for the search API to get metadata for a withdrawn item. The one thing we could do is if the `/rest/items/{UUID}` endpoint returns a 401 we _assume_ that means the item has been withdrawn. It's not the cleanest solution but I'd prefer that over introducing authentication or credentials to the search infrastructure.

**Comment by paulineobps** [comment]
Withdrawn items (and deleted items) should not be available by regular API  Paul.  Since they should be hidden from all public access.  I can get to the record and metadata with my admin login of course.  What else can I send you?

The record is in https://repository.oceanbestpractices.org/admin/withdrawn


Pauline
Pauline SIMPSON
Ocean Best Practices System Project Manager
https://www.oceanbestpractices.org/

UNESCO /IOC Project Office for IODE, InnovOcean Campus – Jacobsenstraat 1 8400 Oostende, Belgium
Email: ***@***.******@***.***>;   Alternate email: ***@***.******@***.***>; Skype: Pauline Simpson
ORCID: 0000-0003-2551-5740


<http://www.iode.org>


________________________________

**Comment by paulineobps** [comment]
we are on 6.3


Pauline
Pauline SIMPSON
Ocean Best Practices System Project Manager
https://www.oceanbestpractices.org/

UNESCO /IOC Project Office for IODE, InnovOcean Campus – Jacobsenstraat 1 8400 Oostende, Belgium
Email: ***@***.******@***.***>;   Alternate email: ***@***.******@***.***>; Skype: Pauline Simpson
ORCID: 0000-0003-2551-5740


<http://www.iode.org>


________________________________

**Comment by paulpilone** [comment]
@paulineobps Understood but it looks like that very feature was discussed and added to the v7 DSpace API: https://github.com/DSpace/DSpace/issues/3245. Not saying anyone should update to that but just pointing out that it was added.

The search API can't (and probably shouldn't) log in as an admin so it can't figure out an item has been withdrawn outside of making assumptions around that Unauthorized response.

**Comment by paulineobps** [comment]
Why would we use a V7 API when we are on V6.3.  We do not foresee upgrading to V7 (which is radically different) for at least another year - it apparently has real problems.

Why should any API be given access to withdrawn/deleted records  - it is not logical - the very reason it is withdrawn is because we do not want users to see it. - and upto this point when a duplicate for example has been with withdrawn - you do not still get two records retrieved in the EDS search  eg.  Methodological Guide to Integrated Coastal Zone Management


Pauline
Pauline SIMPSON
Ocean Best Practices System Project Manager
https://www.oceanbestpractices.org/

UNESCO /IOC Project Office for IODE, InnovOcean Campus – Jacobsenstraat 1 8400 Oostende, Belgium
Email: ***@***.******@***.***>;   Alternate email: ***@***.******@***.***>; Skype: Pauline Simpson
ORCID: 0000-0003-2551-5740


<http://www.iode.org>


________________________________

**Comment by paulpilone** [comment]
Totally understand and I'm definitely not suggesting you upgrade to v7. I was just pointing out the differences between how the two versions behave with respect to withdrawn items.

> Why should any API be given access to withdrawn/deleted records  - it is not logical - the very reason it is withdrawn is because we do not want users to see it. 

I don't necessarily disagree but the purpose of this feature (the index rectifier) is to identify updated or removed items from DSpace and update or remove them from the search interface. If the API can't identify withdrawn items I'm not sure how we can automate removing them from the search interface.

I think we have 2 options:

1. If this feature gets a 401 from the `/rest/items` endpoint we _assume_ that means the item has been withdrawn and remove it from the search index.
2. Only look for updated items in this automated feature. I can add a small function to explicitly delete an item from the search index. This would have to be manually run by someone (Arno?) when an item is withdrawn from DSpace and I would include instructions on how to do that.

**Comment by paulineobps** [comment]
Probably Option 2.

Understanding that OPtion 2 'updated items' can be withdrawn/deleted items;  therefore record should disappear from any search retrieval display; (ie the BOUHALI) and could not be harvested etc;  but also additional metadata and corrections to typos etc etc.


Pauline
Pauline SIMPSON
Ocean Best Practices System Project Manager
https://www.oceanbestpractices.org/

UNESCO /IOC Project Office for IODE, InnovOcean Campus – Jacobsenstraat 1 8400 Oostende, Belgium
Email: ***@***.******@***.***>;   Alternate email: ***@***.******@***.***>; Skype: Pauline Simpson
ORCID: 0000-0003-2551-5740


<http://www.iode.org>


________________________________

**Comment by paulpilone** [comment]
Just to be clear here:

- The index rectifier will be a routine that runs regularly (I believe it's set to every 2 days at the moment) and will identify updated items and queue them for re-ingest so that the new metadata etc. is available in the search interface.
- The index rectifier _will not_ identify or remove items from the search interface.
- I will add a new function that will allow you to delete items from the search interface when they have been withdrawn from DSpace. This function will have to be manually run by a user in AWS. I will include instructions in the documentation on how to run it.

**Comment by paulineobps** [comment]
OK so two processes

  1.  The bulk re-indexing run automatically every 2 days
  2.  For any withdrawn/deleted items that we process we will run a manual process - and that clear out Bouhali appearing on the search interface?


Pauline
Pauline SIMPSON
Ocean Best Practices System Project Manager
https://www.oceanbestpractices.org/

UNESCO /IOC Project Office for IODE, InnovOcean Campus – Jacobsenstraat 1 8400 Oostende, Belgium
Email: ***@***.******@***.***>;   Alternate email: ***@***.******@***.***>; Skype: Pauline Simpson
ORCID: 0000-0003-2551-5740


<http://www.iode.org>


________________________________

**Comment by paulpilone** [comment]
Yes, that would be the setup. I believe Arno has manually run functions before and the removal function would be no different. I'll make sure it's documented.

**Comment by paulineobps** [comment]
thanks Paul


Pauline
Pauline SIMPSON
Ocean Best Practices System Project Manager
https://www.oceanbestpractices.org/

UNESCO /IOC Project Office for IODE, InnovOcean Campus – Jacobsenstraat 1 8400 Oostende, Belgium
Email: ***@***.******@***.***>;   Alternate email: ***@***.******@***.***>; Skype: Pauline Simpson
ORCID: 0000-0003-2551-5740


<http://www.iode.org>


________________________________

**Comment by paulineobps** [comment]
Dear Paul

Please let us know when you have completed this so that we can do a few checks - it will be so good when it is working correctly

thanks

Pauline
Pauline SIMPSON
Ocean Best Practices System Project Manager
https://www.oceanbestpractices.org/

UNESCO /IOC Project Office for IODE, InnovOcean Campus – Jacobsenstraat 1 8400 Oostende, Belgium
Email: ***@***.******@***.***>;   Alternate email: ***@***.******@***.***>; Skype: Pauline Simpson
ORCID: 0000-0003-2551-5740


<http://www.iode.org>


________________________________

**Comment by paulpilone** [comment]
@paulineobps I've deployed these changes to prod and was able to successfully delete the document you listed here https://github.com/iodepo/OceanBestPractices/issues/280#issuecomment-1546097905

If there are other documents that need to be removed @arnounesco should have the permissions to do that. I've added documentation for this feature in this commit here: https://github.com/iodepo/OceanBestPractices/blob/fix/280/fix-index-rectifier/ingest/README.md#deleting-documents

I'm currently running the index rectifier function right now which should queue up items that need to be updated. That will take a few minutes so I hope that in the next few hours you see updated items.

As long as everything runs ok I'll merge these changes into `develop` for @arnounesco. You shouldn't need any deployments as I've already pushed them to production.

**Comment by paulineobps** [comment]
Thanks so much Paul.   You will have seen that Arno is not back until 23 May so have to wait for his comments.

Please confirm - index rectifier function just run today, when will it next run automatically and will it be at a specific time?

Best


Pauline
Pauline SIMPSON
Ocean Best Practices System Project Manager
https://www.oceanbestpractices.org/

UNESCO /IOC Project Office for IODE, InnovOcean Campus – Jacobsenstraat 1 8400 Oostende, Belgium
Email: ***@***.******@***.***>;   Alternate email: ***@***.******@***.***>; Skype: Pauline Simpson
ORCID: 0000-0003-2551-5740


<http://www.iode.org>



________________________________

**Comment by paulpilone** [comment]
@paulineobps Yes, I manually ran it yesterday and it's automatically scheduled to run on a simple 2 day schedule. Arno or someone with equivalent permissions could fine tune that schedule by editing the configuration here: 

https://github.com/iodepo/OceanBestPractices/blob/a31ebd812fc73e986b8aa12f250ac385d6b3665a/cdk/ingest/index.ts#L76 

and re-deploying with the instructions found here: 

https://github.com/iodepo/OceanBestPractices/blob/develop/cdk/README.md#deployment-steps

**Comment by paulineobps** [comment]
Thanks so much Paul.


Pauline
Pauline SIMPSON
Ocean Best Practices System Project Manager
https://www.oceanbestpractices.org/

UNESCO /IOC Project Office for IODE, InnovOcean Campus – Jacobsenstraat 1 8400 Oostende, Belgium
Email: ***@***.******@***.***>;   Alternate email: ***@***.******@***.***>; Skype: Pauline Simpson
ORCID: 0000-0003-2551-5740


<http://www.iode.org>


________________________________

**Comment by paulineobps** [comment]
Arno

are we any closer to upgrading OpenSearch please?  It is urgent but assume this has been closed because until we do the issue will still occur?


Pauline
Pauline SIMPSON
Ocean Best Practices System Project Manager
https://www.oceanbestpractices.org/

UNESCO /IOC Project Office for IODE, InnovOcean Campus – Jacobsenstraat 1 8400 Oostende, Belgium
Email: ***@***.******@***.***>;   Alternate email: ***@***.******@***.***>; Skype: Pauline Simpson

ORCID: https://orcid.org/0000-0003-2551-5740<https://orcid.org/0000-0002-3237-4547>


<http://www.iode.org>


________________________________

**Comment by arnounesco** [comment]
@paulineobps upgrading OpenSearch???????????????????

**Comment by paulineobps** [comment]
@arnounesco this advice to upgrade OpenSearch came from Paul P. to address the issue of the AWS EDS search disappearing for hours (as it just did yesterday)
Cristian requested you to upgrade OpenSearch to test if that fixed the problem - are you able to do that - or what is the problem?

**Comment by arnounesco** [comment]
@paulineobps ok, now I get it, you mean upgrading the subscription, who will pay this, there is already no money to get everything going.....

**Comment by paulineobps** [comment]
thanks Arno - do you know what the cost would be -  an upgrade needs to be tested to see if is solves the problem - and there is no other way than upgrade to test this.

let me know soonest the cost and OBPS  can cover  (unless it is HUGE  but that is unlikely - lets see)


Pauline
Pauline SIMPSON
Ocean Best Practices System Project Manager
https://www.oceanbestpractices.org/

UNESCO /IOC Project Office for IODE, InnovOcean Campus – Jacobsenstraat 1 8400 Oostende, Belgium
Email: ***@***.******@***.***>;   Alternate email: ***@***.******@***.***>; Skype: Pauline Simpson

ORCID: https://orcid.org/0000-0003-2551-5740<https://orcid.org/0000-0002-3237-4547>


<http://www.iode.org>


________________________________
